### PR TITLE
Set acoustic model before loading speaker config in align

### PR DESCRIPTION
**Pull request by fis**
Makes it possible to use model-based CMLLR also in conjunction with align.

### CODE REVIEW

**Comment by fis** [comment]
On closer look, they do seem to be equivalent; for consistency with e.g. phone_probs and mllr, perhaps the constructor approach would be better.

(I tried to avoid that initially just in case the model was expected to be initialized at that time, but that seems to be the way the other applications do it.)

**Comment by psmit** [comment]
Speaking of which, is there any file where it doesn't make sense to add the model directly to the SpeakerConfig?

Shall I change all constructors to include the model? @senarvi do you have an opinion?

**Comment by psmit** [comment]
I made a new pull request that puts the model in all appropriate speaker config constructors #15

**Comment by psmit** [comment]
Closed by #15

**Pull request closed without merging**
